### PR TITLE
hdf5: Support the API changes in 1.13

### PR DESCRIPTION
**Pull request by chuckatkins**

### CODE REVIEW

**Review by brtnfld — DISMISSED** [review]
LGTM.

**Comment by chuckatkins** [comment]
Removed unrelated white space changes

**Review by brtnfld — APPROVED** [review]
LGTM

**Comment by brtnfld** [comment]
Any timeline to get this merged?

**Comment by markcmiller86** [comment]
> Any timeline to get this merged?

Apologies. Taking a look now.

**Review by markcmiller86 — APPROVED** [review]

**Comment by markcmiller86** [comment]
@chuckatkins thank you! 💪🏻

**Pull request merged**
