### PR TITLE
Backport PR#299 to 4.11RC

### PR DESCRIPTION
**Pull request by markcmiller86**
The `SiloWindows` subdir had to be dealt with here too because that dir was removed when CMake was added.

### CODE REVIEW

**Comment by markcmiller86** [comment]
@henryleberre can you pls take a look at this as well. I need to backport your changes to the 4.11 release candidate. Otherwise, the upcoming release won't include them.

**Comment by henryleberre** [comment]
@markcmiller86 Thank you for letting me know, I will take a look at this shortly.

**Comment by markcmiller86** [comment]
@henryleberre do you by chance have any time to check this PR and comment here if ok?

**Comment by henryleberre** [comment]
@markcmiller86 I tried the [mcm86-10jan23-backport-pr267b](https://github.com/LLNL/Silo/tree/mcm86-10jan23-backport-pr267b) branch on an M1 mac. `./configure` worked perfectly (as long as I installed non-Apple compilers) but CMake threw a few errors:
Make: Threw a few errors:
  - Here, it failed to set the project version because it couldn't quite parse the `-pre1` after the version number. https://github.com/LLNL/Silo/blob/ff31cf44faf569b0f3661c7adbfc7f5add1ac8a1/CMakeLists.txt#L66
  - While compiling, the symbol `SIZEOF_OFF64_T` was undefined. This branch appears to be behind main. I had to paste this in to make it work:
https://github.com/LLNL/Silo/blob/d6745d2f200472d65d18f6f9f8076f706c32ef22/CMakeLists.txt#L221-L235
I am not sure how this fixes the issue because `SIZEOF_OFF64_T` never explicitly gets added as a compile definition. It might happen in another file.

On another note, you could maybe add a `Co-authored-by:` line to the commit message!

**Pull request merged**
