### PR TITLE
Fix python testing windows 

### PR DESCRIPTION
**Pull request by biagas**
Merge from 4.11RC, PR's #384, #385.

### CODE REVIEW

**Comment by markcmiller86** [comment]
@biagas I can't tell if you were waiting on approval from me for this because it looks like a merge to main of stuff already reviewed and merged to 4.11RC.

**Review by markcmiller86 — DISMISSED** [review]

**Comment by biagas** [comment]
I don't recall. Had forgotten about this PR. Looks like I need to resolve some conflicts. Will get to this as soon as I can.

**Comment by markcmiller86** [comment]
I tried triggering new CI on develop and I don't think that worked because of conflicts. So, I will wait until those are resolved.

**Comment by biagas** [comment]
Nothing to do here, after resolution of conflicts, just whitespace changes. Deleting this PR.

**Pull request closed without merging**
